version: "2"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - TZ=Europe/London
    volumes:
      - /media/config/pihole/pihole:/etc/pihole/
      - /media/config/pihole/dnsmasq:/etc/dnsmasq.d/
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always
    ports:
      - 53:53
      - 67:67
      - 80:80
      - 443:443
